### PR TITLE
Courses subsection added

### PR DESCRIPTION
**Pull request by sloreti**
Hello!  [Exponent](https://www.tryexponent.com/), an interview prep platform for tech, just published a 17-hour course on interviewing for engineering management roles. (Full disclosure, I work as a software engineer there.) 

[https://www.tryexponent.com/courses/engineering-management](https://www.tryexponent.com/courses/engineering-management)

This PR adds a Courses subsection to the Learning section, with Exponent's Engineering Management Interview Course linked.

Thanks for your consideration!

### CODE REVIEW

**Comment by ixaxaar** [comment]
Thanks for the PR. 

I see a courses section as a good idea. 
Since you work with the edtech community, would you be able to include other courses like the google project management cert from coursera etc?

**Comment by ixaxaar** [comment]
PR closed by mistake.

**Comment by sloreti** [comment]
Added a few more courses, including the Google project management course from Coursera. Let me know what you think!

Truthfully, there are hardly any full-blown courses available online that focus on the EM role, or interviewing to become an EM (which was a large part of the reason we made one).

**Comment by ixaxaar** [comment]
Thanks for the effort! 

Indeed the taught courses available for an engineer to transition to an EM role are very limited which is scary.

**Pull request merged**
